name = "dashera"
description = "DASHER Terminal Emulator"
version = "0.13.1"
licenses = "MIT"
website = "https://github.com/SMerrony/dashera"

authors = ["Stephen Merrony"]
maintainers = ["Stephen Merrony <merrony@gmail.com>"]
maintainers-logins = ["SMerrony"]

tags = ["gtk", "terminal", "dasher", "emulator",]

executables = ["dashera"]

[[depends-on]]
gtkada = "^23.0.0"
